repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml
    -   id: detect-private-key
    -   id: end-of-file-fixer
        exclude: '^(.*\.sh|.*\.dbc)$'  # Exclude config and DBC
    -   id: trailing-whitespace
        exclude: '^(.*\.sh|.*\.dbc)$'  # Exclude config and DBC
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.1
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
