version: "3.9"
services:
  influx:
    container_name: influx_v2
    image: influxdb:latest
    ports:
      - 8080:8086
    volumes:
      - $PWD/src:/home/influxdb/scripts:rw          # Main script
      - $PWD/templates:/home/influxdb/templates:rw  # InfluxDB dashboards
      - influx-data:/var/lib/influxdb2
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: "unless-stopped"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUX_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUX_ORG}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_TOKEN}
      DOCKER_INFLUXDB_INIT_BUCKET: garbage
      INFLUXDB_HTTP_AUTH_ENABLED: false
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
volumes:
  influx-data:
    name: "influx_db"