version: "3.9"
services:
  core:
   build:
     context: .
     dockerfile: Dockerfile
   container_name: solis_rx
   depends_on:
     - influx
  #  devices:  # Comment out if using can or test_can adapters
  #    - /dev/ttyUSB0:/dev/ttyUSB0
   environment:
   # Modify this values in the environment file (.env).
     # Valid adapters are: 
     #  can - Use CAN adapter to read data (P&P)
     #  usb - Use USB adapter to read data (xBee)
     #  test_can - Mock CAN adapter to run test
     #  test_usb - Mock USB adapter to run test
     TUCN_INPUT_ADAPTER: ${TUCN_INPUT_ADAPTER}
     # Valid run modes are: 
     #  debug
     #  release
     TUCN_RUN_MODE: ${TUCN_RUN_MODE}
     DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_TOKEN}
     DOCKER_INFLUXDB_INIT_ORG: ${INFLUX_ORG}
   networks:
     - solis-network
   restart: on-failure
  influx:
    container_name: influx_v2
    environment:
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_TOKEN}
      DOCKER_INFLUXDB_INIT_BUCKET: UNKNOWN
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUX_ORG}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_PASSWORD}
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUX_USERNAME}
      INFLUXDB_HTTP_AUTH_ENABLED: false
    hostname: database
    image: influxdb:2.7.5-alpine
    networks:
      - solis-network
    ports:
      - 8080:8086
    restart: on-failure
    volumes:
      - influxdb_storage:/var/lib/influxdb2  # Persistence storage
  grafana:
    container_name: grafana
    depends_on:
      - influx
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${INFLUX_PASSWORD}
      GF_SECURITY_ADMIN_USER: ${INFLUX_USERNAME}
    hostname: interface
    image: grafana/grafana-oss:10.0.3
    networks:
      - solis-network
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - grafana_storage:/var/lib/grafana  # Persistence storage
networks:
  solis-network:
volumes:
  influxdb_storage:
    name: "influxdb_persitence_storage"
  grafana_storage:
    name: "grafana_persitence_storage"
