version: '3.9'
services:
  influxdb:
    image: influxdb:latest
    ports:
      - '80:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=solis_telemetry
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_HTTP_AUTH_ENABLED=true
  grafana:
    image: grafana/grafana:latest
    ports:
      - '8080:3000'
    volumes:
      - assets:/var/lib/grafana
      - assets/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
  # chronograf:
  #   image: chronograf:latest
  #   ports:
  #     - '127.0.0.1:8888:8888'
  #   volumes:
  #     - chronograf-storage:/var/lib/chronograf
  #   depends_on:
  #     - influxdb
  #   environment:
  #     - INFLUXDB_URL=127.0.0.1:8086
  #     - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
  #     - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
volumes:
  influxdb-storage:
  grafana-storage:
  # chronograf-storage:
