[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
dynamic = ["version"]
name = "Telemetry_RX"
description = "Escort vehicle telemetry reciever, with support for USART & TCP/IP adapters."
authors = [{name = "Vorobiov Mihail", email = "mihail.vorobiov@gmail.com"}]
license = "MIT"
readme = "README.md"
classifiers = [
  "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.12"
dependencies = [
  "cantools~=39.4.0",
  "crc~=7.0.0",
  "influxdb-client[ciso]~=1.44.0",
  "pyserial==3.5",
]
keywords = ["telemetry", "solis"]

[project.optional-dependencies]
dev = [
  "pre-commit",
  "pytest",
  "ruff",
]

[project.scripts]
start_telemetry = "telemetry_rx.main:start"

[tool.hatch.version]
path = "src/telemetry_rx/version.py"

[tool.hatch.build.targets.wheel]
include = ["src/**"]

[tool.hatch.build.targets.sdist]
include = ["src/**"]

[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]
line-length = 130
indent-width = 4
target-version = "py311"

[tool.ruff.lint]
fixable = ["ALL"]
unfixable = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
